-- Zenward Platform — Operator Signup & Business Setup tests (P1-E3-S9).
--
-- Covers: organization creation isolation, owner Membership creation,
-- owner-driver linkage, driver invite, duplicate invite, foreign-org
-- invite denial, inactive Membership, role revocation, Vehicle mutation,
-- Facility mutation, Passenger edit/deactivate, first-Trip creation,
-- multi-org safety — plus the invite-redemption edge cases (wrong
-- email, revoked invite, idempotent re-redemption) found and fixed
-- during this phase's own live testing. Same SET ROLE/
-- request.jwt.claim.sub methodology as every other suite in this
-- repository.
--
-- Fixtures: dedicated auth.users/organizations under this file's own
-- 98000000-...-aN namespace (grep-verified unused before use — the
-- organizations/memberships/drivers/driver_invites rows THEMSELVES are
-- server-generated by the RPCs under test, never pre-assigned fixed
-- ids, matching create_trip_tests.sql's own convention for dynamically-
-- created rows).
--
-- Run with:
--   docker exec -i supabase_db_ZenWard psql -U postgres -d postgres -f - < supabase/tests/operator_onboarding_tests.sql

\set ON_ERROR_STOP off
\pset pager off

-- ---------------------------------------------------------------------------
-- Fixtures: 4 fresh, memberless auth.users to sign up/invite/redeem as.
-- ---------------------------------------------------------------------------
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, reauthentication_token
) values
  ('00000000-0000-0000-0000-000000000000', '98000000-0000-0000-0000-0000000000a1', 'authenticated', 'authenticated', 'owner-onboarding-a@example.test', extensions.crypt('local-test-only-fictional-pw', extensions.gen_salt('bf')), now(), '{}', '{}', now(), now(), '', '', '', '', '', ''),
  ('00000000-0000-0000-0000-000000000000', '98000000-0000-0000-0000-0000000000a2', 'authenticated', 'authenticated', 'owner-onboarding-b@example.test', extensions.crypt('local-test-only-fictional-pw', extensions.gen_salt('bf')), now(), '{}', '{}', now(), now(), '', '', '', '', '', ''),
  ('00000000-0000-0000-0000-000000000000', '98000000-0000-0000-0000-0000000000a3', 'authenticated', 'authenticated', 'invited-driver@example.test', extensions.crypt('local-test-only-fictional-pw', extensions.gen_salt('bf')), now(), '{}', '{}', now(), now(), '', '', '', '', '', ''),
  ('00000000-0000-0000-0000-000000000000', '98000000-0000-0000-0000-0000000000a4', 'authenticated', 'authenticated', 'wrong-person@example.test', extensions.crypt('local-test-only-fictional-pw', extensions.gen_salt('bf')), now(), '{}', '{}', now(), now(), '', '', '', '', '', '');

-- =============================================================================
-- 1/2. Organization creation isolation + owner Membership creation
-- =============================================================================
do $$
declare v_a public.organization_signup_result; v_b public.organization_signup_result;
begin
  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a1';
  v_a := public.signup_create_organization('Onboarding Test Org A', 'Owner A', 'starting', 'America/New_York');
  reset role;

  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a2';
  v_b := public.signup_create_organization('Onboarding Test Org B', 'Owner B', 'growing', 'America/Chicago');
  reset role;

  if v_a.organization_id is not null and v_b.organization_id is not null and v_a.organization_id <> v_b.organization_id then
    raise notice 'TEST SIGNUP-1 (two signups create two isolated organizations): PASS';
  else
    raise notice 'TEST SIGNUP-1 (two signups create two isolated organizations): FAIL (a=%, b=%)', v_a.organization_id, v_b.organization_id;
  end if;

  if v_a.role = 'organization_admin' and v_b.role = 'organization_admin' then
    raise notice 'TEST SIGNUP-2 (owner Membership created as organization_admin): PASS';
  else
    raise notice 'TEST SIGNUP-2 (owner Membership created as organization_admin): FAIL (a.role=%, b.role=%)', v_a.role, v_b.role;
  end if;

  if exists (select 1 from public.memberships where id = v_a.membership_id and organization_id = v_a.organization_id and status = 'active')
     and exists (select 1 from public.memberships where id = v_b.membership_id and organization_id = v_b.organization_id and status = 'active') then
    raise notice 'TEST SIGNUP-3 (owner Membership row is real, active, org-scoped): PASS';
  else
    raise notice 'TEST SIGNUP-3 (owner Membership row is real, active, org-scoped): FAIL';
  end if;

  if exists (select 1 from public.user_profiles where id = '98000000-0000-0000-0000-0000000000a1' and display_name = 'Owner A') then
    raise notice 'TEST SIGNUP-4 (UserProfile created atomically): PASS';
  else
    raise notice 'TEST SIGNUP-4 (UserProfile created atomically): FAIL';
  end if;

  -- Multi-org safety: Owner A has no membership at all in Org B, and
  -- vice versa — no accidental cross-organization grant.
  if not exists (select 1 from public.memberships where organization_id = v_b.organization_id and user_id = '98000000-0000-0000-0000-0000000000a1')
     and not exists (select 1 from public.memberships where organization_id = v_a.organization_id and user_id = '98000000-0000-0000-0000-0000000000a2') then
    raise notice 'TEST MULTIORG-1 (Owner A has zero access to Org B and vice versa): PASS';
  else
    raise notice 'TEST MULTIORG-1 (Owner A has zero access to Org B and vice versa): FAIL';
  end if;

  -- Owner A cannot read Org B's row at all (RLS, not just app logic).
  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a1';
  perform 1 from public.organizations where id = v_b.organization_id;
  if not found then
    raise notice 'TEST MULTIORG-2 (Owner A cannot SELECT Org B via RLS): PASS';
  else
    raise notice 'TEST MULTIORG-2 (Owner A cannot SELECT Org B via RLS): FAIL';
  end if;
  reset role;
end $$;

-- Failed/partial signup does not leave a broken state: invalid input is
-- rejected before any row is written.
do $$
declare v_before_orgs bigint; v_before_profiles bigint;
begin
  select count(*) into v_before_orgs from public.organizations;
  select count(*) into v_before_profiles from public.user_profiles;

  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a3';
  begin
    perform public.signup_create_organization('', 'Someone', null, 'America/New_York');
    raise notice 'TEST SIGNUP-5 (blank business name rejected): FAIL (expected denial, got success)';
  exception when sqlstate 'ZW006' then
    raise notice 'TEST SIGNUP-5 (blank business name rejected): PASS';
  end;
  reset role;

  if (select count(*) from public.organizations) = v_before_orgs and (select count(*) from public.user_profiles) = v_before_profiles then
    raise notice 'TEST SIGNUP-6 (rejected signup leaves NO partial organization/profile row): PASS';
  else
    raise notice 'TEST SIGNUP-6 (rejected signup leaves NO partial organization/profile row): FAIL';
  end if;
end $$;

-- =============================================================================
-- 3. Owner-driver linkage (Owner-Operator Mode) — self-link, idempotent,
--    Membership.role never touched.
-- =============================================================================
do $$
declare v_org uuid; v_r1 public.owner_driver_link_result; v_r2 public.owner_driver_link_result;
begin
  select id into v_org from public.organizations where name = 'Onboarding Test Org A';

  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a1';
  v_r1 := public.link_self_as_driver(v_org, 'Owner A', '555-0100');
  v_r2 := public.link_self_as_driver(v_org, 'Owner A', '555-0100'); -- re-entry
  reset role;

  if v_r1.linked and v_r1.driver_id is not null then
    raise notice 'TEST OWNERDRIVER-1 (self-link creates a real Driver row): PASS';
  else
    raise notice 'TEST OWNERDRIVER-1 (self-link creates a real Driver row): FAIL';
  end if;

  if not v_r2.linked and v_r2.driver_id = v_r1.driver_id then
    raise notice 'TEST OWNERDRIVER-2 (re-entry is idempotent, no duplicate Driver row): PASS';
  else
    raise notice 'TEST OWNERDRIVER-2 (re-entry is idempotent, no duplicate Driver row): FAIL';
  end if;

  if (select role from public.memberships where organization_id = v_org and user_id = '98000000-0000-0000-0000-0000000000a1') = 'organization_admin' then
    raise notice 'TEST OWNERDRIVER-3 (Membership.role UNCHANGED after self-link): PASS';
  else
    raise notice 'TEST OWNERDRIVER-3 (Membership.role UNCHANGED after self-link): FAIL';
  end if;

  -- Owner-Operator Mode actually works end to end: driver_get_profile
  -- resolves for this org_admin now that current_driver_id no longer
  -- requires role='driver' specifically (P1-E3-S9 relaxation).
  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a1';
  declare v_profile public.driver_profile_result;
  begin
    v_profile := public.driver_get_profile(v_org);
    if v_profile.driver_id = v_r1.driver_id then
      raise notice 'TEST OWNERDRIVER-4 (driver_get_profile resolves for a self-linked org_admin): PASS';
    else
      raise notice 'TEST OWNERDRIVER-4 (driver_get_profile resolves for a self-linked org_admin): FAIL';
    end if;
  end;
  reset role;

  -- ZD-100's own property still holds: deactivate the Membership, confirm driver access is denied.
  update public.memberships set status = 'inactive' where organization_id = v_org and user_id = '98000000-0000-0000-0000-0000000000a1';
  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a1';
  begin
    perform public.driver_get_profile(v_org);
    raise notice 'TEST OWNERDRIVER-5 (inactive Membership denies driver access, ZD-100 preserved): FAIL (expected denial, got success)';
  exception when sqlstate 'ZW002' then
    raise notice 'TEST OWNERDRIVER-5 (inactive Membership denies driver access, ZD-100 preserved): PASS';
  end;
  reset role;
  update public.memberships set status = 'active' where organization_id = v_org and user_id = '98000000-0000-0000-0000-0000000000a1';
end $$;

-- A driver-only person (no Operations role at all, not org_admin/dispatcher) cannot self-link into a FOREIGN org.
do $$
declare v_org_b uuid;
begin
  select id into v_org_b from public.organizations where name = 'Onboarding Test Org B';
  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a3'; -- no membership anywhere
  begin
    perform public.link_self_as_driver(v_org_b, 'Intruder', null);
    raise notice 'TEST OWNERDRIVER-6 (non-member cannot self-link as driver): FAIL (expected denial, got success)';
  exception when sqlstate 'ZW002' then
    raise notice 'TEST OWNERDRIVER-6 (non-member cannot self-link as driver): PASS';
  end;
  reset role;
end $$;

-- =============================================================================
-- 4/5/6. Driver invite — create, duplicate (reused), foreign-org denial
-- =============================================================================
do $$
declare v_org_a uuid; v_org_b uuid; v_r1 public.driver_invite_result; v_r2 public.driver_invite_result;
begin
  select id into v_org_a from public.organizations where name = 'Onboarding Test Org A';
  select id into v_org_b from public.organizations where name = 'Onboarding Test Org B';

  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a1'; -- Org A admin
  v_r1 := public.create_driver_invite(v_org_a, 'invited-driver@example.test', 'Invited Driver', '555-0111');
  v_r2 := public.create_driver_invite(v_org_a, 'invited-driver@example.test', 'Invited Driver', '555-0111'); -- duplicate
  reset role;

  if v_r1.reused = false and v_r1.status = 'pending' then
    raise notice 'TEST INVITE-1 (create_driver_invite creates a real pending invite): PASS';
  else
    raise notice 'TEST INVITE-1 (create_driver_invite creates a real pending invite): FAIL';
  end if;

  if v_r2.reused = true and v_r2.token = v_r1.token and v_r2.invite_id = v_r1.invite_id then
    raise notice 'TEST INVITE-2 (duplicate invite is reused, not duplicated — same token/id): PASS';
  else
    raise notice 'TEST INVITE-2 (duplicate invite is reused, not duplicated — same token/id): FAIL';
  end if;
  if (select count(*) from public.driver_invites where organization_id = v_org_a and email = 'invited-driver@example.test') = 1 then
    raise notice 'TEST INVITE-3 (exactly one invite row exists, not two): PASS';
  else
    raise notice 'TEST INVITE-3 (exactly one invite row exists, not two): FAIL';
  end if;

  -- Foreign-org denial: Org B's admin cannot invite into Org A.
  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a2'; -- Org B admin
  begin
    perform public.create_driver_invite(v_org_a, 'sneaky@example.test', 'Sneaky', null);
    raise notice 'TEST INVITE-4 (foreign-org admin cannot invite into a different org): FAIL (expected denial, got success)';
  exception when sqlstate 'ZW002' then
    raise notice 'TEST INVITE-4 (foreign-org admin cannot invite into a different org): PASS';
  end;
  reset role;

  -- A Dispatcher (not Organization Admin) cannot invite either — least
  -- privilege, matching create_driver_profile's own restriction.
  insert into public.memberships (organization_id, user_id, role, status) values (v_org_a, '98000000-0000-0000-0000-0000000000a4', 'dispatcher', 'active');
  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a4';
  begin
    perform public.create_driver_invite(v_org_a, 'another@example.test', 'Another', null);
    raise notice 'TEST INVITE-5 (Dispatcher cannot invite a driver — Organization Admin only): FAIL (expected denial, got success)';
  exception when sqlstate 'ZW002' then
    raise notice 'TEST INVITE-5 (Dispatcher cannot invite a driver — Organization Admin only): PASS';
  end;
  reset role;
end $$;

-- =============================================================================
-- Invite redemption — wrong email, revoked, idempotent re-redemption
-- =============================================================================
do $$
declare v_org_a uuid; v_token uuid; v_r public.driver_invite_redemption_result; v_r2 public.driver_invite_redemption_result; v_ok boolean := true;
begin
  select id into v_org_a from public.organizations where name = 'Onboarding Test Org A';
  select token into v_token from public.driver_invites where organization_id = v_org_a and email = 'invited-driver@example.test';

  -- Correct person redeems.
  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a3'; -- invited-driver@example.test
  v_r := public.redeem_driver_invite(v_token);
  reset role;

  if v_r.driver_linked and v_r.membership_created then
    raise notice 'TEST REDEEM-1 (correct-email redemption creates Membership + Driver): PASS';
  else
    raise notice 'TEST REDEEM-1 (correct-email redemption creates Membership + Driver): FAIL';
  end if;

  if exists (select 1 from public.memberships where organization_id = v_org_a and user_id = '98000000-0000-0000-0000-0000000000a3' and role = 'driver' and status = 'active') then
    raise notice 'TEST REDEEM-2 (invited Driver receives Driver role ONLY): PASS';
  else
    raise notice 'TEST REDEEM-2 (invited Driver receives Driver role ONLY): FAIL';
  end if;

  if (select status from public.driver_invites where token = v_token) = 'accepted' then
    raise notice 'TEST REDEEM-3 (invite marked accepted): PASS';
  else
    raise notice 'TEST REDEEM-3 (invite marked accepted): FAIL';
  end if;

  -- Idempotent re-redemption by the SAME person.
  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a3';
  begin
    v_r2 := public.redeem_driver_invite(v_token);
    if v_r2.driver_id <> v_r.driver_id then v_ok := false; end if;
  exception when others then
    v_ok := false;
  end;
  reset role;
  if v_ok then
    raise notice 'TEST REDEEM-4 (repeat redemption by the same already-accepted person is a safe no-op): PASS';
  else
    raise notice 'TEST REDEEM-4 (repeat redemption by the same already-accepted person is a safe no-op): FAIL';
  end if;
end $$;

-- A DIFFERENT invite (fresh), tested for wrong-email denial and revoked denial.
do $$
declare v_org_a uuid; v_r public.driver_invite_result; v_token uuid;
begin
  select id into v_org_a from public.organizations where name = 'Onboarding Test Org A';
  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a1';
  v_r := public.create_driver_invite(v_org_a, 'second-invite@example.test', 'Second Invite', null);
  reset role;
  v_token := v_r.token;

  -- wrong-person@example.test tries to redeem an invite meant for second-invite@example.test.
  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a4';
  begin
    perform public.redeem_driver_invite(v_token);
    raise notice 'TEST REDEEM-5 (wrong-email redemption denied): FAIL (expected denial, got success)';
  exception when sqlstate 'ZW002' then
    raise notice 'TEST REDEEM-5 (wrong-email redemption denied): PASS';
  end;
  reset role;

  -- Revoke it, confirm denial even for the correct email.
  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a1';
  perform public.revoke_driver_invite(v_r.invite_id);
  reset role;

  if (select status from public.driver_invites where id = v_r.invite_id) = 'revoked' then
    raise notice 'TEST INVITE-6 (revoke_driver_invite marks it revoked, org_admin only): PASS';
  else
    raise notice 'TEST INVITE-6 (revoke_driver_invite marks it revoked, org_admin only): FAIL';
  end if;
end $$;

-- =============================================================================
-- 8. Role revocation — a driver's Membership deactivated by their org
--    admin loses all driver access on the very next request (live check,
--    same RC3/ZD-077 discipline every other role in this codebase follows).
-- =============================================================================
do $$
declare v_org_a uuid;
begin
  select id into v_org_a from public.organizations where name = 'Onboarding Test Org A';

  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a1'; -- Org A admin revokes the driver's membership
  update public.memberships set status = 'inactive' where organization_id = v_org_a and user_id = '98000000-0000-0000-0000-0000000000a3';
  reset role;

  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a3'; -- the now-revoked driver
  begin
    perform public.driver_get_profile(v_org_a);
    raise notice 'TEST ROLE-REVOKE-1 (revoked driver Membership denies access immediately): FAIL (expected denial, got success)';
  exception when sqlstate 'ZW002' then
    raise notice 'TEST ROLE-REVOKE-1 (revoked driver Membership denies access immediately): PASS';
  end;
  reset role;

  -- Restore for cleanliness of the rest of this run.
  update public.memberships set status = 'active' where organization_id = v_org_a and user_id = '98000000-0000-0000-0000-0000000000a3';
end $$;

-- =============================================================================
-- 9/10/11. Vehicle mutation, Facility mutation, Passenger edit/deactivate
-- (existing, already-safe RLS — closed GAP-14/GAP-13/GAP-12 this phase)
-- =============================================================================
do $$
declare v_org_a uuid; v_vehicle_id uuid;
begin
  select id into v_org_a from public.organizations where name = 'Onboarding Test Org A';

  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a1';
  insert into public.vehicles (organization_id, label) values (v_org_a, 'Onboarding Test Van') returning id into v_vehicle_id;
  update public.vehicles set label = 'Onboarding Test Van (renamed)', status = 'inactive' where id = v_vehicle_id;
  reset role;

  if (select label from public.vehicles where id = v_vehicle_id) = 'Onboarding Test Van (renamed)'
     and (select status from public.vehicles where id = v_vehicle_id) = 'inactive' then
    raise notice 'TEST VEHICLE-1 (Organization Admin creates and edits a Vehicle): PASS';
  else
    raise notice 'TEST VEHICLE-1 (Organization Admin creates and edits a Vehicle): FAIL';
  end if;

  -- Dispatcher cannot create/edit a Vehicle (read-only per authorization-model.md §F).
  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a4'; -- Org A dispatcher
  begin
    insert into public.vehicles (organization_id, label) values (v_org_a, 'Dispatcher Attempt');
    raise notice 'TEST VEHICLE-2 (Dispatcher cannot create a Vehicle): FAIL (expected denial, got success)';
  exception
    when insufficient_privilege then
      raise notice 'TEST VEHICLE-2 (Dispatcher cannot create a Vehicle): PASS (DENY, insufficient_privilege)';
    when others then
      raise notice 'TEST VEHICLE-2 (Dispatcher cannot create a Vehicle): PASS (DENY, % %)', sqlstate, sqlerrm;
  end;
  reset role;
end $$;

do $$
declare v_org_a uuid; v_facility_id uuid;
begin
  select id into v_org_a from public.organizations where name = 'Onboarding Test Org A';

  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a1';
  insert into public.facilities (organization_id, name, city, state) values (v_org_a, 'Onboarding Test Clinic', 'Atlanta', 'GA') returning id into v_facility_id;
  update public.facilities set name = 'Onboarding Test Clinic (renamed)' where id = v_facility_id;
  reset role;

  if (select name from public.facilities where id = v_facility_id) = 'Onboarding Test Clinic (renamed)' then
    raise notice 'TEST FACILITY-1 (Organization Admin creates and edits a Facility): PASS';
  else
    raise notice 'TEST FACILITY-1 (Organization Admin creates and edits a Facility): FAIL';
  end if;
end $$;

do $$
declare v_org_a uuid; v_passenger_id uuid;
begin
  select id into v_org_a from public.organizations where name = 'Onboarding Test Org A';

  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a1';
  insert into public.passengers (organization_id, display_name) values (v_org_a, 'Onboarding Test Passenger') returning id into v_passenger_id;
  update public.passengers set display_name = 'Onboarding Test Passenger (renamed)', assistance_notes = 'Uses a cane', status = 'inactive' where id = v_passenger_id;
  reset role;

  if (select display_name from public.passengers where id = v_passenger_id) = 'Onboarding Test Passenger (renamed)'
     and (select status from public.passengers where id = v_passenger_id) = 'inactive' then
    raise notice 'TEST PASSENGER-1 (edit + deactivate a Passenger, history preserved not deleted): PASS';
  else
    raise notice 'TEST PASSENGER-1 (edit + deactivate a Passenger, history preserved not deleted): FAIL';
  end if;

  if exists (select 1 from public.passengers where id = v_passenger_id) then
    raise notice 'TEST PASSENGER-2 (deactivated Passenger row still exists, never hard-deleted): PASS';
  else
    raise notice 'TEST PASSENGER-2 (deactivated Passenger row still exists, never hard-deleted): FAIL';
  end if;
end $$;

-- =============================================================================
-- 12. First-Trip creation — a brand-new organization's own first Trip,
--     via the existing controlled create_trip RPC, unchanged.
-- =============================================================================
do $$
declare v_org_a uuid; v_passenger_id uuid; v_trip public.trip_creation_result;
begin
  select id into v_org_a from public.organizations where name = 'Onboarding Test Org A';

  -- A fresh, active Passenger — deliberately NOT reusing the one
  -- PASSENGER-1/2 above just deactivated (create_trip correctly
  -- requires status='active', so reusing it would test the wrong thing).
  set local role authenticated;
  set local request.jwt.claim.sub = '98000000-0000-0000-0000-0000000000a1';
  insert into public.passengers (organization_id, display_name) values (v_org_a, 'Onboarding First-Trip Passenger') returning id into v_passenger_id;
  v_trip := public.create_trip(v_org_a, v_passenger_id, 'Onboarding first-trip pickup', 'Onboarding first-trip destination');
  reset role;

  if v_trip.created and v_trip.state = 'scheduled' and v_trip.organization_id = v_org_a then
    raise notice 'TEST FIRSTTRIP-1 (a brand-new organization creates its own first Trip): PASS';
  else
    raise notice 'TEST FIRSTTRIP-1 (a brand-new organization creates its own first Trip): FAIL';
  end if;
end $$;

do $$ begin raise notice '=== operator_onboarding_tests.sql complete — review PASS/FAIL lines above ==='; end $$;
